# Generated by Django 3.2.5 on 2021-08-05 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('kind', models.CharField(choices=[('meski', 'Męski'), ('damski', 'Damski')], max_length=10)),
                ('condition', models.CharField(choices=[('ds', 'DS'), ('vnds', 'VNDS'), ('4/5', '4/5'), ('3/5', '3/5'), ('2/5', '2/5'), ('1/5', '1/5')], max_length=5)),
                ('shoes_size', models.CharField(choices=[('36.0', '36.0'), ('36.5', '36.5'), ('37.0', '37.0'), ('37.5', '37.5'), ('38.0', '38.0'), ('38.5', '38.5'), ('39.0', '39.0'), ('39.5', '39.5'), ('40.0', '40.0'), ('40.5', '40.5'), ('41.0', '41.0'), ('41.5', '41.5'), ('42.0', '42.0'), ('42.5', '42.5'), ('43.0', '43.0'), ('43.5', '43.5'), ('44.0', '44.0'), ('44.5', '44.5'), ('45.0', '45.0'), ('45.5', '45.5'), ('46.0', '46.0'), ('46.5', '46.5'), ('47.0', '47.0'), ('47.5', '47.5'), ('48.0', '48.0'), ('48.5', '48.5'), ('49.0', '49.0'), ('49.5', '49.5'), ('50.0', '50.0')], max_length=5)),
                ('clothes_size', models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=5)),
                ('fit', models.CharField(choices=[('slimfit', 'Slim Fit'), ('regular', 'Regular'), ('oversize', 'Oversize')], max_length=10)),
                ('colorway', models.CharField(choices=[('brown', 'Brown'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('black', 'Black'), ('grey', 'Grey'), ('white', 'White'), ('multi', 'Multi')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sneakpick.brand')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sneakpick.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
