# Generated by Django 4.1.1 on 2023-03-02 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_time', models.CharField(max_length=100, null=True)),
                ('method', models.CharField(choices=[('Meeting', 'Meeting'), ('Polish Post', 'Polish Post'), ('DPD courier', 'DPD courier')], max_length=15)),
                ('city', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Delivery Method',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('brand', models.CharField(choices=[('nike', 'nike'), ('adidas', 'adidas'), ('supreme', 'supreme'), ('puma', 'puma'), ('new balance', 'new balance'), ('vans', 'vans'), ('louis vuitton', 'louis vuitton'), ('palace', 'palace'), ('diadora', 'diadora'), ('moschino', 'moschino'), ('reebok', 'reebok'), ('balenciaga', 'balenciaga'), ('calvin klein', 'calvin klein'), ('gucci', 'gucci'), ('dsquared2', 'dsquared2'), ('lacoste', 'lacoste'), ('yeezy', 'yeezy'), ('off-white', 'off-white'), ('converse', 'converse'), ('stone island', 'stone island'), ('the north face', 'the north face'), ('ralph lauren', 'ralph lauren'), ('guess', 'guess'), ('tommy hilfiger', 'tommy hilfiger'), ('vlone', 'vlone'), ('inne', 'inne')], max_length=250)),
                ('category', models.CharField(choices=[('sneakersy', 'sneakersy'), ('hoodie', 'hoodie'), ('teesy', 'teesy'), ('koszule', 'koszule'), ('crewnecki', 'crewnecki'), ('longsleevy', 'longsleevy'), ('katany', 'katany'), ('kurtki', 'kurtki'), ('płaszcze', 'płaszcze'), ('spodnie', 'spodnie'), ('szale', 'szale'), ('portfele', 'portfele'), ('plecaki', 'plecaki'), ('zegarki', 'zegarki'), ('czapki', 'czapki'), ('belty', 'belty'), ('bielizna', 'bielizna'), ('inne', 'inne')], max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('kind', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=5)),
                ('condition', models.CharField(choices=[('ds', 'ds'), ('vnds', 'vnds'), ('4/5', '4/5'), ('3/5', '3/5'), ('2/5', '2/5'), ('1/5', '1/5')], max_length=5)),
                ('size', models.CharField(blank=True, choices=[('xxs', 'xxs'), ('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('36.0', '36.0'), ('36.5', '36.5'), ('37.0', '37.0'), ('37.5', '37.5'), ('38.0', '38.0'), ('38.5', '38.5'), ('39.0', '39.0'), ('39.5', '39.5'), ('40.0', '40.0'), ('40.5', '40.5'), ('41.0', '41.0'), ('41.5', '41.5'), ('42.0', '42.0'), ('42.5', '42.5'), ('43.0', '43.0'), ('43.5', '43.5'), ('44.0', '44.0'), ('44.5', '44.5'), ('45.0', '45.0'), ('45.5', '45.5'), ('46.0', '46.0'), ('46.5', '46.5'), ('47.0', '47.0'), ('47.5', '47.5'), ('48.0', '48.0'), ('48.5', '48.5'), ('49.0', '49.0'), ('49.5', '49.5'), ('50.0', '50.0')], max_length=5, null=True)),
                ('fit', models.CharField(blank=True, choices=[('slim fit', 'slim fit'), ('regular', 'regular'), ('oversize', 'oversize')], max_length=10)),
                ('colorway', models.CharField(choices=[('brown', 'brown'), ('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('purple', 'purple'), ('pink', 'pink'), ('black', 'black'), ('grey', 'grey'), ('white', 'white'), ('multi', 'multi')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='published', max_length=10)),
                ('bought', models.BooleanField(default=False)),
                ('for_trade', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
