# Generated by Django 3.2 on 2022-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('nike', 'nike'), ('adidas', 'adidas'), ('supreme', 'supreme'), ('puma', 'puma'), ('new balance', 'new balance'), ('vans', 'vans'), ('louis vuitton', 'louis vuitton'), ('palace', 'palace'), ('diadora', 'diadora'), ('moschino', 'moschino'), ('reebok', 'reebok'), ('balenciaga', 'balenciaga'), ('calvin klein', 'calvin klein'), ('gucci', 'gucci'), ('dsquared2', 'dsquared2'), ('lacoste', 'lacoste'), ('yeezy', 'yeezy'), ('off-white', 'off-white'), ('converse', 'converse'), ('stone island', 'stone island'), ('the north face', 'the north face'), ('ralph lauren', 'ralph lauren'), ('guess', 'guess'), ('tommy hilfiger', 'tommy hilfiger'), ('vlone', 'vlone'), ('inne', 'inne')], max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sneakersy', 'sneakersy'), ('hoodie', 'hoodie'), ('teesy', 'teesy'), ('koszule', 'koszule'), ('crewnecki', 'crewnecki'), ('longsleevy', 'longsleevy'), ('katany', 'katany'), ('kurtki', 'kurtki'), ('płaszcze', 'płaszcze'), ('spodnie', 'spodnie'), ('szale', 'szale'), ('portfele', 'portfele'), ('plecaki', 'plecaki'), ('zegarki', 'zegarki'), ('czapki', 'czapki'), ('belty', 'belty'), ('bielizna', 'bielizna'), ('inne', 'inne')], max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorway',
            field=models.CharField(choices=[('brown', 'brown'), ('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('purple', 'purple'), ('pink', 'pink'), ('black', 'black'), ('grey', 'grey'), ('white', 'white'), ('multi', 'multi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('ds', 'ds'), ('vnds', 'vnds'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, choices=[('slim fit', 'slim fit'), ('regular', 'regular'), ('oversize', 'oversize')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('męski', 'męski'), ('damski', 'damski')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('xxs', 'xxs'), ('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('36.0', '36.0'), ('36.5', '36.5'), ('37.0', '37.0'), ('37.5', '37.5'), ('38.0', '38.0'), ('38.5', '38.5'), ('39.0', '39.0'), ('39.5', '39.5'), ('40.0', '40.0'), ('40.5', '40.5'), ('41.0', '41.0'), ('41.5', '41.5'), ('42.0', '42.0'), ('42.5', '42.5'), ('43.0', '43.0'), ('43.5', '43.5'), ('44.0', '44.0'), ('44.5', '44.5'), ('45.0', '45.0'), ('45.5', '45.5'), ('46.0', '46.0'), ('46.5', '46.5'), ('47.0', '47.0'), ('47.5', '47.5'), ('48.0', '48.0'), ('48.5', '48.5'), ('49.0', '49.0'), ('49.5', '49.5'), ('50.0', '50.0')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='published', max_length=10),
        ),
    ]
