# Generated by Django 3.2 on 2022-08-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220807_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('ds', 'ds'), ('vnds', 'vnds'), ('4/5', '4/5'), ('3/5', '3/5'), ('2/5', '2/5'), ('1/5', '1/5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=5),
        ),
    ]
