# Generated by Django 3.2 on 2022-09-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220816_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_trade',
            field=models.BooleanField(default=False),
        ),
    ]
