export const brands = [
    "Nike",
    "Adidas",
    "Supreme",
    "Puma",
    "New Balance",
    "Vans",
    "Louis Vuitton",
    "Palace",
    "Diadora",
    "Reebok",
    "Balenciaga",
    "Lacoste",
    "Yeezy",
    "Off-White",
    "Converse",
    "Stone Island",
    "The North Face",
    "Ralph Lauren",
    "Guess",
    "Tommy Hilfiger",
    "VLONE",
    "Inne",
]