export enum routes {
  DOMAIN = "http://localhost:8000",
  HOME = "/",
  WTB = "/wtb",
  WTS = "/wts",
  WTT = "/wtt",
  TALK = "/talk",
  PROXY = "/proxy",
  STEAL = "/steal",
  FAQ = "/faq",
  SUPPORT = "/support",
  BUSINESSCONTACT = "/businesscontact",
  FOLLOWED = "/followed",
  ITEM = "/wtb/:item",
  PROFILE = "/profile/:user",
  PROFILE_SETTINGS = "/settings/profile",
  ACCOUNT_SETTINGS = "/settings/account",
  PASSWORD_CHANGE = "/settings/account/password",
  EMAIL_CHANGE = "/settings/account/email",
  DEFAULT_SEARCH = "limit=24&offset=0&ordering=1",
  CATEGORY = "category=",
  BRAND = "brand=",
  POPULAR = "?limit=24&offset=0&ordering=1",
  NEWEST = "?limit=24&offset=0&ordering=5",
  FORGOTTEN_PASSWORD = "/password",
  USER_PROFILE_COMMENTS = "/profile/:user/comments",
  USER_PROFILE_PRODUCTS = "/profile/:user/products",
  ORDERS = "/orders",
  ORDER = "/products/:item/order",
  CALLOUT = "/products/:item/callout",
  STATUTE = "/statute",
  CATEGORY_PATH = "/wtb?category={category}&limit=24&offset=0&ordering=1",
  BRAND_PATH = "/wtb?brand={brand}&limit=24&offset=0&ordering=1",
}

export enum endpoints {
  USER_IMAGES = "/static/user/images/",
  HOST = "http://127.0.0.1:8000/api/",
  MAIN = "",
  IMAGES = "/static/product/images/",
  LOGIN = "user/login/",
  BLACKLIST = "user/logout/blacklist/",
  REGISTER = "user/register/",
  BUMP = "bump/",
  FOLLOW = "user/follow/",
  USER = "user/",
  USER_PRODUCTS_LIST = "user_list/",
  ME = "user/me/",
  EDIT = "user/edit/",
  POST_FOLLOWED = "user/followed/{id}/",
  GET_FOLLOWED = "user/followed/",
}
