export enum routes {
  DOMAIN = "http://localhost:8000",
  HOME = "/",
  WTB = "/wtb",
  WTS = "/wts",
  WTT = "/wtt",
  TALK = "/talk",
  PROXY = "/proxy",
  STEAL = "/steal",
  FAQ = "/faq",
  SUPPORT = "/support",
  BUSINESSCONTACT = "/businesscontact",
  FOLLOWED = "/followed",
  ITEM = "/wtb/:item",
  DEFAULT_PROFILE = "/profile/",
  PROFILE = "/profile/:user",
  PROFILE_SETTINGS = "/settings/profile",
  ACCOUNT_SETTINGS = "/settings/account",
  PASSWORD_CHANGE = "/settings/account/password",
  EMAIL_CHANGE = "/settings/account/email",
  DEFAULT_SEARCH = "limit=24&offset=0&ordering=1",
  CATEGORY = "category=",
  BRAND = "brand=",
  POPULAR = "?limit=24&offset=0&ordering=3",
  NEWEST = "?limit=24&offset=0&ordering=4",
}

export enum endpoints {
  HOST = "http://127.0.0.1:8000/api/",
  MAIN = "",
  IMAGES = "/static/product/images/",
  LOGIN = "user/login/",
  BLACKLIST = "user/logout/blacklist/",
  REGISTER = "user/register/",
  BUMP = "bump/",
  FOLLOW = "user/follow/",
  USER = "user/",
  USER_PRODUCTS_LIST = "user_list/",
  ME = "user/me/",
  EDIT = "user/edit/",
  FOLLOWED = "user/followed/",
}
