export const routes = {
  DOMAIN: "http://localhost:8000",
  HOME: "/",
  WTB: "/wtb",
  WTS: "/wts",
  WTT: "/wtt",
  TALK: "/talk",
  PROXY: "/proxy",
  STEAL: "/steal",
  FAQ: "/faq",
  SUPPORT: "/support",
  BUSINESSCONTACT: "/businesscontact",
  ITEM: "/wtb/:item",
  PROFILE: "/profile/:user",
  PROFILE_SETTINGS: "/settings/profile",
  ACCOUNT_SETTINGS: "/settings/account",
  DEFAULT_SEARCH: "limit=24&offset=0&ordering=1",
  CATEGORY: "category=",
  BRAND: "brand=",
};

export const endpoints = {
  MAIN: "",
  IMAGES: "/static/product/images/",
  LOGIN: "user/login/",
  BLACKLIST: "user/logout/blacklist/",
  REGISTER: "user/register/",
  BUMP: "bump/",
  USER: "user/",
  USER_PRODUCTS_LIST: "user_list/",
  ME: "user/me/",
  EDIT: "user/edit/",
};
