# Generated by Django 4.1.1 on 2023-03-02 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bumps',
            field=models.ManyToManyField(blank=True, related_name='question_bumps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='talk.question'),
        ),
    ]
