# Generated by Django 4.1.1 on 2022-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_question_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='item',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('id', 'id'), ('lc', 'lc'), ('pc', 'pc'), ('fit', 'fit'), ('other', 'other')], max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
