# Generated by Django 3.2 on 2022-09-01 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Steal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('markdown', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('rocket', models.BooleanField(default=False)),
                ('alert', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steal.store')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
