# Generated by Django 4.1.1 on 2023-03-02 19:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('promka', 'promka'), ('drop', 'drop'), ('ea', 'ea'), ('steal', 'steal')], max_length=10)),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(max_length=1000)),
                ('markdown', models.CharField(blank=True, max_length=20, null=True)),
                ('rocket', models.BooleanField(blank=True, default=False, null=True)),
                ('alert', models.BooleanField(blank=True, default=False, null=True)),
                ('photo', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
            ],
        ),
    ]
