# Generated by Django 3.2 on 2022-09-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steal',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='steal.store'),
        ),
    ]
