# Generated by Django 4.1.1 on 2023-03-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
    ]
