# Generated by Django 3.2 on 2022-09-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steal', '0002_alter_steal_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steal',
            name='alert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='steal',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steal',
            name='markdown',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='steal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='steal',
            name='rocket',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='steal',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='steal.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.CharField(max_length=50),
        ),
    ]
