# Generated by Django 3.2 on 2022-09-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steal', '0003_auto_20220901_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steal',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='steal.store'),
        ),
    ]
