# Generated by Django 3.2 on 2022-09-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steal', '0004_alter_steal_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steal',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='steal.store'),
        ),
    ]
